<?php

namespace IAdvize\VdmBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VdmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VdmRepository extends EntityRepository
{
    /**
     * Enregistre la VDM
     * 
     * @param VDM $newVdm
     */
     public function saveVdm(Vdm $newVdm)
    {
        $this->getEntityManager()
                ->persist($newVdm);
        $this->getEntityManager()
                ->flush();
    }
    
    /**
     * Sélectionne les VDM suivant les critères
     * 
     * array type $param
     * @return array
     */
    public function getVdmFromParam($param) {
        $qb = $this->getEntityManager()
            ->createQueryBuilder("vdm");
        
        $qb->select('vdm');
        $qb->from("IAdvizeVdmBundle:Vdm", "vdm");
        if(!is_null($param->author)) {
            $qb->where("vdm.auteur = '". $param->author ."'");
        }
        if(!is_null($param->from)) {
            $qb->where("vdm.datep > '". $param->from ."'");
        }
        if(!is_null($param->to)) {
            $qb->where("vdm.datep < '". $param->to ."'");
        }
        return $qb->getQuery()
                ->getResult();
    }
}
